force-app/objects/SFDC_Survey_Question_Response__c/SFDC_Survey_Question_Response__c.object-meta.xml
<CustomObject>
    <description>shadow object for Salesforce Survey Response</description>
    <label>SFDC Survey Question Response</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>SFDC Survey Question Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SFDC Survey Question Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/objects/SFDC_Survey_Question_Response__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NPS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/objects/SFDC_Survey_Question_Response__c/fields/Number_Response__c.field-meta.xml
<CustomField>
    <fullName>Number_Response__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/objects/SFDC_Survey_Question_Response__c/fields/Survey_Invitation__c.field-meta.xml
<CustomField>
    <fullName>Survey_Invitation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Invitation</label>
    <referenceTo>SurveyInvitation</referenceTo>
    <relationshipLabel>SFDC Survey Question Responses</relationshipLabel>
    <relationshipName>SFDC_Survey_Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/objects/SFDC_Survey_Question_Response__c/fields/Survey_Question__c.field-meta.xml
<CustomField>
    <fullName>Survey_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Survey Question</label>
    <referenceTo>SurveyQuestion</referenceTo>
    <relationshipLabel>SFDC Survey Question Responses</relationshipLabel>
    <relationshipName>SFDC_Survey_Question_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/objects/SFDC_Survey_Question_Response__c/fields/Text_Response__c.field-meta.xml
<CustomField>
    <fullName>Text_Response__c</fullName>
    <label>Value</label>
    <type>TextArea</type>
</CustomField>

force-app/classes/SurveyQuestionResponseTriggerHandler.cls
public without sharing class SurveyQuestionResponseTriggerHandler {

    public static void handle(List<SurveyQuestionResponse> questionResponses) {
        
        List<SFDC_Survey_Question_Response__c> shadowQuestionResponses = new List<SFDC_Survey_Question_Response__c>();
    
        System.debug('SurveyQuestionResponseTrigger > questionResponses: ' + questionResponses.size());
    
        for (SurveyQuestionResponse questionResponse : questionResponses) {
    
            System.debug('SurveyQuestionResponseTrigger > questionResponse: ' + questionResponse);
    
            SFDC_Survey_Question_Response__c shadowQuestionResponse = new SFDC_Survey_Question_Response__c();
            shadowQuestionResponse.Survey_Invitation__c = questionResponse.InvitationId;
            shadowQuestionResponse.Survey_Question__c = questionResponse.QuestionId;
    
            SurveyQuestion question = [SELECT Name, QuestionType, SurveyPageId FROM SurveyQuestion
                WHERE Id = :questionResponse.QuestionId LIMIT 1];
            
            //SurveyPage page = [SELECT Name FROM SurveyPage
            //    WHERE Id = :question.SurveyPageId LIMIT 1];
    
            shadowQuestionResponse.Question__c = question.Name;
            
            String textResponse = questionResponse.ResponseShortText;
    
            if ((questionResponse.Datatype == 'Number')
                    || (question.QuestionType == 'Slider') || (question.QuestionType == 'NPS') || (question.QuestionType == 'Rating')                    
					) {
                Integer numberResponse = Integer.valueof(textResponse);
                shadowQuestionResponse.Number_Response__c = numberResponse;
            } else if (questionResponse.Datatype == 'String') {
                shadowQuestionResponse.Text_Response__c = textResponse;
            }
    
            //shadowQuestionResponse.Category__c = page.Name;
            if (question.QuestionType == 'NPS') {
                shadowQuestionResponse.Category__c = 'NPS';
            } else {
                shadowQuestionResponse.Category__c = 'Other';
            }
            
            shadowQuestionResponses.add(shadowQuestionResponse);
    
        } // end for
    
        insert shadowQuestionResponses;        
    } // end handle
    
}